### ISSUE TITLE
Converting dataframe tempView to correct schema 

### ISSUE THREAD

**Issue by gmdfalk** [adrianulbona/osm-parquetizer#6]
Hey,

this is more of a support request since the real issue is my unfamiliarity with scala but i really hope you'll humor me.

I followed this tutorial: https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4082562773728035/2089274675795739/3712305628257488/latest.html

But i get binary values where i am expecting strings.
```
%spark2.spark
val nodesDF = spark.read.parquet("/tmp/geo/bremen-filtered.osm.pbf.node.parquet")
nodesDF.createOrReplaceTempView("nodes")
nodesDF.show()
---result----
+-----+-------+-------------+---------+-------+--------------------+--------------------+--------------------+
|   id|version|    timestamp|changeset|    uid|            user_sid|                tags|             members|
+-----+-------+-------------+---------+-------+--------------------+--------------------+--------------------+
| 2952|     26|1488545617000| 46548312| 339581|[6E 79 75 72 69 6...|[[[B@2343598a,[B@...|[[293249683,[B@75...|
| 3800|      3|1491746258000| 47593689|  44217|       [6B 6A 6F 6E]|[[[B@16219edd,[B@...|[[4287246,[B@3111...|
```

```
%spark2.spark
nodesDF.printSchema()
nodesDF.select($"tags".getItem(1)).head().get(0)
---result---
root
 |-- id: long (nullable = true)
 |-- version: integer (nullable = true)
 |-- timestamp: long (nullable = true)
 |-- changeset: long (nullable = true)
 |-- uid: integer (nullable = true)
 |-- user_sid: binary (nullable = true)
 |-- tags: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- key: binary (nullable = true)
 |    |    |-- value: binary (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
res11: Any = [[B@5d543cb8,[B@ce6535f]
```

The schema recognized all string types, i.e. `user_sid` and `key` as well as `value` of `element`, as binary.
How do i convert them back to strings or better yet, apply the correct schema at the start?

Thanks!

**Comment by gmdfalk** [comment]
Some additional info.
spark: 2.1.0.2.6.0.3-8
scala: 2.11.8
jdk: 1.8.0_131

The parquet schema according to spark-shell:
```
message spark_schema {
  required int64 id;
  optional int32 version;
  optional int64 timestamp;
  optional int64 changeset;
  optional int32 uid;
  optional binary user_sid;
  repeated group tags {
    required binary key;
    optional binary value;
  }
  required double latitude;
  required double longitude;
}
```

This is what spark makes of it:
```
StructType(StructField(id,LongType,false), StructField(version,IntegerType,true), StructField(timestamp,LongType,true), StructField(changeset,LongType,true), StructField(uid,IntegerType,true), StructField(user_sid,BinaryTzpe,true), StructField(tags,ArrayType(StructType(StructField(key,BinaryType,false), StructField(value,BinaryType,true)),false),false), StructField(latitude,DoubleType,false), StructField(longitude,DoubleType,false))
```

**Comment by adrianulbona** [comment]
Hi @serialoverflow 

In Parquet there is no string type, but byte arrays (binary type). To tell Spark that it has to handle the the binary content as strings you have to set `spark.sql.parquet.binaryAsString` to `true`. 

If you have control over SparkSession creation you can specify it there or you if are using Zeppelin then go to Interpreters and add the property to the Spark interpreter. 

Let me know if this works.

**Comment by gmdfalk** [comment]
yes, it does work!
perfect timing, i just hit run with that setting when you posted your response.

I do use zeppelin and it exposes the SQLContext as sqlContext so the following worked
```
sqlContext.setConf("spark.sql.parquet.binaryAsString","true")
val nodesDF = spark.read.parquet("/tmp/osm/romania-latest.osm.pbf.node.parquet") 
```

thanks again

**Comment by adrianulbona** [comment]
great! don't hesitate to ask other questions!
